local AnimationConfig = {}

AnimationConfig.Fists = {

	Idle = "rbxassetid://79642318244455",

	Attacks = {
		"rbxassetid://115665597710295"
	}

}

AnimationConfig.Sword = {

	Idle = "rbxassetid://79642318244455",

	Attacks = {
		"rbxassetid://80462361581761",
		"rbxassetid://115522764063327",
		"rbxassetid://106427010281676",
		"rbxassetid://123583962593241"
	}

}

return AnimationConfig