local BonusPools = {}

BonusPools.Weapon = {

	{Id="StrongVsEsoteric", Values={5,10,15,20}},
	{Id="StrongVsSemiHuman", Values={3,5,8,10}},
	{Id="StrongVsOrc", Values={5,10,15,20}},
	{Id="StrongVsDevil", Values={5,10,15,20}},
	{Id="StrongVsAnimal", Values={5,10,15,20}},
	{Id="StrongVsVampire", Values={5,10,15,20}},

	{Id="PenetrationChance", Values={3,5,8,10}},
	{Id="CriticalChance", Values={3,5,8,10}},

	{Id="PoisonChance", Values={2,4,6,8}},
	{Id="BlockChance", Values={2,4,6,8}},
	{Id="SlowChance", Values={2,4,6,8}},

	{Id="CastingSpeed", Values={5,10,15,20}},

	{Id="STR", Values={3,6,9,12}},
	{Id="DEX", Values={3,6,9,12}},
	{Id="INT", Values={3,6,9,12}},
	{Id="VIT", Values={3,6,9,12}}
}

BonusPools.Armor = {

	{Id="SwordDefense", Values={5,10,12,15}},
	{Id="TwoHandDefense", Values={5,10,12,15}},
	{Id="DaggerDefense", Values={5,10,12,15}},
	{Id="BellDefense", Values={5,10,12,15}},
	{Id="FanDefense", Values={5,10,12,15}},
	{Id="ArrowResistance", Values={5,10,12,15}},

	{Id="MagicResistance", Values={5,10,12,15}},
	{Id="LightningResistance", Values={5,10,12,15}},
	{Id="WindResistance", Values={5,10,12,15}},
	{Id="FireResistance", Values={5,10,12,15}},

	{Id="LifeSteal", Values={3,5,8,10}},
	{Id="ManaSteal", Values={3,5,8,10}},

	{Id="MaxHP", Values={500,1000,1500,2000}},
	{Id="MaxMP", Values={50,100,150,200}},

	{Id="ReflectPhysicalDamage", Values={3,5,8,10}},

	{Id="AttackValue", Values={10,20,35,50}},

	{Id="CastingSpeed", Values={5,10,15,20}}
}

BonusPools.Helmet = {

	{Id="StrongVsEsoteric", Values={5,10,15,20}},
	{Id="StrongVsSemiHuman", Values={3,5,8,10}},
	{Id="StrongVsOrc", Values={5,10,15,20}},
	{Id="StrongVsDevil", Values={5,10,15,20}},
	{Id="StrongVsAnimal", Values={5,10,15,20}},
	{Id="StrongVsVampire", Values={5,10,15,20}},

	{Id="MagicResistance", Values={5,10,12,15}},
	{Id="LightningResistance", Values={5,10,12,15}},
	{Id="WindResistance", Values={5,10,12,15}},
	{Id="FireResistance", Values={5,10,12,15}},

	{Id="PoisonChance", Values={2,4,6,8}},

	{Id="ManaSteal", Values={3,5,8,10}},

	{Id="HPRegen", Values={10,15,20,30}},
	{Id="MPRegen", Values={10,15,20,30}},

	{Id="AttackSpeed", Values={2,4,6,8}},

	{Id="ArrowDodge", Values={5,8,10,15}}
}

BonusPools.Shield = {

	{Id="StrongVsEsoteric", Values={5,10,15,20}},
	{Id="StrongVsSemiHuman", Values={3,5,8,10}},
	{Id="StrongVsOrc", Values={5,10,15,20}},
	{Id="StrongVsDevil", Values={5,10,15,20}},
	{Id="StrongVsAnimal", Values={5,10,15,20}},
	{Id="StrongVsVampire", Values={5,10,15,20}},

	{Id="StunResistance", Values={5,8,10,15}},
	{Id="SlowResistance", Values={5,8,10,15}},

	{Id="ReflectPhysicalDamage", Values={3,5,8,10}},
	{Id="BlockChance", Values={5,8,12,15}},

	{Id="BonusExperience", Values={5,10,15,20}},
	{Id="DoubleYangDrop", Values={5,10,15,20}},

	{Id="STR", Values={3,6,9,12}},
	{Id="DEX", Values={3,6,9,12}},
	{Id="INT", Values={3,6,9,12}},
	{Id="VIT", Values={3,6,9,12}}
}
BonusPools.Bracelet = {

	{Id="StrongVsEsoteric", Values={5,10,15,20}},
	{Id="StrongVsSemiHuman", Values={3,5,8,10}},
	{Id="StrongVsOrc", Values={5,10,15,20}},
	{Id="StrongVsDevil", Values={5,10,15,20}},
	{Id="StrongVsAnimal", Values={5,10,15,20}},
	{Id="StrongVsVampire", Values={5,10,15,20}},

	{Id="MagicResistance", Values={5,10,12,15}},
	{Id="LightningResistance", Values={5,10,12,15}},
	{Id="WindResistance", Values={5,10,12,15}},
	{Id="FireResistance", Values={5,10,12,15}},

	{Id="PenetrationChance", Values={3,5,8,10}},
	{Id="LifeSteal", Values={3,5,8,10}},
	{Id="ManaSteal", Values={3,5,8,10}},

	{Id="MaxHP", Values={500,1000,1500,2000}},
	{Id="MaxMP", Values={20,40,60,80}},

	{Id="DoubleDrop", Values={5,10,15,20}}

}
BonusPools.Necklace = {

	{Id="SwordDefense", Values={5,10,12,15}},
	{Id="TwoHandDefense", Values={5,10,12,15}},
	{Id="DaggerDefense", Values={5,10,12,15}},
	{Id="BellDefense", Values={5,10,12,15}},
	{Id="FanDefense", Values={5,10,12,15}},

	{Id="ArrowResistance", Values={5,10,12,15}},

	{Id="BlockChance", Values={2,4,6,8}},
	{Id="PenetrationChance", Values={3,5,8,10}},
	{Id="CriticalChance", Values={3,5,8,10}},

	{Id="ManaAbsorb", Values={3,5,8,10}},
	{Id="ManaSteal", Values={3,5,8,10}},

	{Id="MaxHP", Values={500,1000,1500,2000}},

	{Id="HPRegen", Values={10,15,20,30}},
	{Id="MPRegen", Values={10,15,20,30}},

	{Id="BonusExperience", Values={5,10,15,20}},
	{Id="DoubleYangDrop", Values={5,10,15,20}}

}
BonusPools.Earrings = {

	{Id="StrongVsEsoteric", Values={5,10,15,20}},
	{Id="StrongVsSemiHuman", Values={3,5,8,10}},
	{Id="StrongVsOrc", Values={5,10,15,20}},
	{Id="StrongVsDevil", Values={5,10,15,20}},
	{Id="StrongVsAnimal", Values={5,10,15,20}},
	{Id="StrongVsVampire", Values={5,10,15,20}},

	{Id="SwordDefense", Values={5,10,12,15}},
	{Id="TwoHandDefense", Values={5,10,12,15}},
	{Id="DaggerDefense", Values={5,10,12,15}},
	{Id="BellDefense", Values={5,10,12,15}},
	{Id="FanDefense", Values={5,10,12,15}},

	{Id="ArrowResistance", Values={5,10,12,15}},

	{Id="ManaSteal", Values={3,5,8,10}},

	{Id="PoisonResistance", Values={2,3,4,5}},

	{Id="DoubleDrop", Values={5,10,15,20}},

	{Id="MoveSpeed", Values={5,10,15,20}}

}
BonusPools.Shoes = {

	{Id="SwordDefense", Values={5,10,12,15}},
	{Id="TwoHandDefense", Values={5,10,12,15}},
	{Id="DaggerDefense", Values={5,10,12,15}},
	{Id="BellDefense", Values={5,10,12,15}},
	{Id="FanDefense", Values={5,10,12,15}},

	{Id="ArrowResistance", Values={5,10,12,15}},

	{Id="CriticalChance", Values={3,5,8,10}},

	{Id="BlockChance", Values={2,4,6,8}},
	{Id="SlowChance", Values={2,4,6,8}},

	{Id="MaxHP", Values={500,1000,1500,2000}},
	{Id="MaxMP", Values={20,40,60,80}},

	{Id="BonusExperience", Values={5,10,15,20}},

	{Id="AttackSpeed", Values={2,4,6,8}},

	{Id="DoubleYangDrop", Values={5,10,15,20}},

	{Id="ArrowDodge", Values={5,8,10,15}}

}

return BonusPools